name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      TEMP_SECRET: "some silly value"
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AUTO_SECRET: ${{ secrets.AUTO_SECRET }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TOKEN_RESPONSE_CODE: ${{ secrets.TOKEN_RESPONSE_CODE }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: dotnet restore TestApp/
    - name: Build Test
      run: dotnet build TestApp/ --no-restore
    - name: Test (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project TestApp/TestApp.csproj --no-build Test/Debug/net6.0/TestApp.dll 
