name: Build Test Youtube

on:
  schedule:
    - cron: '8 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      TEMP_SECRET: "some silly value"
      AUTO_SECRET: ${{ secrets.AUTO_SECRET }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TOKEN_RESPONSE_CODE: ${{ secrets.TOKEN_RESPONSE_CODE }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      EXPIRES_IN_SECONDS: ${{ secrets.EXPIRES_IN_SECONDS }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      ISSUED: ${{ secrets.ISSUED }}
      ISSUED_UTC: ${{ secrets.ISSUED_UTC }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      SCOPE: ${{ secrets.SCOPE }}
      TOKEN_TYPE: ${{ secrets.TOKEN_TYPE }}
      GOOGLE_ACCESS_TOKEN: ${{ secrets.GOOGLE_ACCESS_TOKEN }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab # v1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: dotnet restore TestApp/
    - name: Build Test
      run: dotnet build TestApp/ --no-restore
    - name: Test (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project TestApp/TestApp.csproj --no-build Test/Debug/net6.0/TestApp.dll 
